// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA357558mdalPzi75FTAezcOo0EjQFLOLQ',
    appId: '1:792003398181:web:ffe161b786fd392cfecdcc',
    messagingSenderId: '792003398181',
    projectId: 'my-weather-c3d23',
    authDomain: 'my-weather-c3d23.firebaseapp.com',
    databaseURL: 'https://my-weather-c3d23.firebaseio.com',
    storageBucket: 'my-weather-c3d23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkPAbLQYbwdxomJGI8Abnv2_-GhZP56eg',
    appId: '1:792003398181:android:919df8f0b2da8e7cfecdcc',
    messagingSenderId: '792003398181',
    projectId: 'my-weather-c3d23',
    databaseURL: 'https://my-weather-c3d23.firebaseio.com',
    storageBucket: 'my-weather-c3d23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1chzBpmoG13c10dYGMD-0YxpLpEOo9Gg',
    appId: '1:792003398181:ios:2d19283977000e06fecdcc',
    messagingSenderId: '792003398181',
    projectId: 'my-weather-c3d23',
    databaseURL: 'https://my-weather-c3d23.firebaseio.com',
    storageBucket: 'my-weather-c3d23.appspot.com',
    iosClientId:
        '792003398181-cm9d1h8b3jenpjqlpd578vucfktonkes.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1chzBpmoG13c10dYGMD-0YxpLpEOo9Gg',
    appId: '1:792003398181:ios:2d19283977000e06fecdcc',
    messagingSenderId: '792003398181',
    projectId: 'my-weather-c3d23',
    databaseURL: 'https://my-weather-c3d23.firebaseio.com',
    storageBucket: 'my-weather-c3d23.appspot.com',
    iosClientId:
        '792003398181-cm9d1h8b3jenpjqlpd578vucfktonkes.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebook',
  );
}
